/* eslint-disable @next/next/no-img-element -- Product screenshots are intentional source assets and must remain compatible with the static export. */

import type { Metadata } from "next";
import { fpeCheckoutLinks } from "./fpeCheckoutLinks";
import { ProductLanguageSwitcher, productLocalePaths, type ProductLocale } from "./ProductLanguageSwitcher";
import { SiteFooter, SiteHeader } from "./SiteChrome";

type Copy = {
  lang: string;
  title: string;
  description: string;
  nav: string[];
  hero: { eyebrow: string; promise: string; lede: string; trial: string; guide: string; demo: string; proofs: string[]; alt: string };
  scenario: { label: string; title: string; intro: string; without: string; withoutBody: string; with: string; withBody: string; quote: string };
  demo: { label: string; title: string; body: string; caption: string; fallback: string };
  trial: { label: string; title: string; body: string; cards: [string, string][] };
  pricing: { label: string; title: string; body: string; recommended: string; multi: string; singleAudience: string; proAudience: string; single: string[]; pro: string[]; choose: string; compare: string; note: string };
  benefits: { label: string; title: string; body: string; items: [string, string][] };
  workflow: { label: string; title: string; steps: [string, string][] };
  ai: { eyebrow: string; title: string; body: string; bullets: string[]; alt: string; action: string };
  clean: { label: string; title: string; items: [string, string][] };
  requirements: { label: string; title: string; body: string; rows: [string, string][] };
  trust: string[];
  faq: { label: string; title: string; items: [string, string][] };
  cta: { eyebrow: string; title: string; body: string; button: string; status: string };
  legal: string;
};

const copy: Record<Exclude<ProductLocale, "es">, Copy> = {
  en: {
    lang: "en",
    title: "Frontend Product Editor + AI for PrestaShop | Pep Logar",
    description: "Edit the PrestaShop product you are already viewing without searching for it again in the Back Office. Full 14-day trial, permanent free mode and perpetual licences.",
    nav: ["Demo", "Trial", "Plans", "Features", "Compatibility", "FAQ"],
    hero: { eyebrow: "Product · Chrome / Edge · PrestaShop 1.6–9", promise: "Fix the product you are already viewing.", lede: "Edit prices, stock, references and content from your shop's public product page, without finding the product again in the Back Office.", trial: "Try free for 14 days", guide: "Download visual guide", demo: "Watch demo", proofs: ["No card for the trial", "Permanent free mode", "One-time payment", "No modules"], alt: "Editing a PrestaShop product from its public page" },
    scenario: { label: "A real situation", title: "‘Can I buy it if it is out of stock?’", intro: "A customer calls because the storefront says there is no stock. You know the item is available; the product only needs updating.", without: "Without the extension", withoutBody: "Open the Back Office, search the catalogue, locate quantities, update stock, save, and return to the shop while the customer waits.", with: "With the extension", withBody: "Stay on the same page the customer is viewing. Change the quantity, review it and save. No second product search.", quote: "‘You can complete the order now. Sorry for the inconvenience.’" },
    demo: { label: "See it in action", title: "From catalogue to saved change.", body: "A real workflow: identify the product, edit it, use AI and verify the result.", caption: "Demo · 46 seconds · PrestaShop 9", fallback: "Your browser cannot play this video." },
    trial: { label: "Start without risk", title: "Try everything. Decide later.", body: "The trial starts only after the first successful connection to your PrestaShop shop.", cards: [["14 full days", "Edit, review, verify, undo, dictate and use AI with every feature enabled."], ["No card required", "Install, connect your shop and test the real workflow before buying."], ["Permanent free mode", "After the trial, keep identifying products and opening their exact Back Office page."]] },
    pricing: { label: "Perpetual licences", title: "One payment. Your tool.", body: "Choose by number of shops and browser profiles. Both licences include every commercial feature.", recommended: "Recommended", multi: "Multi-shop", singleAudience: "For the owner or admin team of one PrestaShop shop.", proAudience: "For businesses managing several shops or small multi-shop teams.", single: ["1 PrestaShop shop", "Up to 6 Chrome or Edge profiles", "All commercial features", "Perpetual licence, no monthly fees"], pro: ["2 to 5 PrestaShop shops", "Up to 20 Chrome or Edge profiles", "All commercial features", "Perpetual licence, no monthly fees"], choose: "Choose", compare: "Compare plans", note: "Prices exclude applicable taxes. Purchase and licence delivery are handled by Lemon Squeezy as merchant of record." },
    benefits: { label: "What changes", title: "Less searching. More catalogue fixed.", body: "The extension follows your workflow instead of forcing you away from the product you are reviewing.", items: [["Edit where you spot the problem", "Open the public page and change the product without locating it again."], ["Save through PrestaShop", "Use the original forms and verify the result after saving."], ["Work with combinations", "Recognise the selected combination and update the right stock or reference."], ["Improve content with AI", "Work on names, descriptions, metadata and other editable Back Office fields."], ["Dictate, then decide", "Review punctuation and polish the transcript before inserting it."], ["Keep control", "Local history, undo preparation and configurable prompts."]] },
    workflow: { label: "How it works", title: "Four steps. No duplicate search.", steps: [["Connect", "Sign in to the Back Office and save its path in the side panel."], ["Browse", "Use the shop like a customer and spot the product that needs attention."], ["Edit", "Open the floating control and change commercial data or jump to the admin page."], ["Verify", "Save through PrestaShop and confirm automatically that the change was applied."]] },
    ai: { eyebrow: "AI inside the Back Office", title: "Work with the field. Not a separate box.", body: "The assistant appears when you write or select content in a native field and prepares a proposal before inserting it.", bullets: ["Improve, expand, shorten or correct.", "Optimise for SEO and translate.", "Apply rich formatting when the field supports HTML.", "Editable prompts and several providers, including local models."], alt: "AI assistant working on a PrestaShop description", action: "Work with this field" },
    clean: { label: "Clean installation", title: "Your shop is not modified.", items: [["Not a module", "No files, tables or overrides are installed in PrestaShop."], ["Uses your real session", "Works with the forms and permissions of the open Back Office."], ["Leaves no residue", "Uninstall the extension without leaving code behind in the shop."], ["Keys under your control", "AI credentials stay locally in the browser profile."]] },
    requirements: { label: "Compatibility", title: "What you need to start.", body: "A straightforward setup with no server access and no changes to shop code.", rows: [["Browser", "Desktop Google Chrome or Microsoft Edge"], ["PrestaShop", "Adapters for 1.6 · 1.7 · 8 · 9"], ["Session", "Back Office open in the same browser profile"], ["Installation", "Browser extension, no PrestaShop module"], ["AI", "Optional cloud HTTPS provider or compatible local model"], ["Interface", "Spanish, English, French, Italian, German and Portuguese"]] },
    trust: ["One-time payment", "No subscription", "Chrome and Edge", "PrestaShop 1.6–9", "6 languages", "Local data"],
    faq: { label: "Frequently asked questions", title: "What matters before installing.", items: [["When does the 14-day trial start?", "After the first successful PrestaShop connection, not when the extension is installed."], ["What remains after the trial?", "The permanent free mode still identifies the product or combination and opens its exact Back Office page."], ["Is the licence a subscription?", "No. Shop and Pro are perpetual, one-time-payment licences."], ["Does it install a module?", "No. It is a Chrome and Edge extension and does not modify PrestaShop code."], ["Where is the AI key stored?", "In the local storage of the browser profile. Requests go directly to the selected provider."], ["Can I edit products with variants?", "Yes. The extension detects the selected combination and works with the corresponding data."]] },
    cta: { eyebrow: "Coming soon", title: "Install, connect and decide after trying it.", body: "The extension will be available in the Chrome Web Store with a full 14-day trial and perpetual licences through Lemon Squeezy.", button: "Compare plans", status: "Installation link available after publication" },
    legal: "Before installing or purchasing, read the Spanish privacy policy and licence, support and refund terms.",
  },
  pt: {
    lang: "pt-PT", title: "Frontend Product Editor + AI para PrestaShop | Pep Logar", description: "Edite o produto PrestaShop que já está a ver, sem voltar a procurá-lo no Back Office. Teste completo de 14 dias, modo gratuito e licenças perpétuas.", nav: ["Demonstração", "Teste", "Planos", "Funções", "Compatibilidade", "Perguntas"],
    hero: { eyebrow: "Produto · Chrome / Edge · PrestaShop 1.6–9", promise: "Corrija o produto que já está a ver.", lede: "Edite preços, stock, referências e conteúdos a partir da página pública do produto, sem voltar a localizá-lo no Back Office.", trial: "Testar grátis durante 14 dias", guide: "Descarregar guia visual", demo: "Ver demonstração", proofs: ["Sem cartão para testar", "Modo gratuito permanente", "Pagamento único", "Sem módulos"], alt: "Edição de um produto PrestaShop a partir da página pública" },
    scenario: { label: "Uma situação real", title: "«Posso comprar se não há stock?»", intro: "Um cliente telefona porque a loja indica que não há stock. Sabe que o artigo existe; só falta atualizar o produto.", without: "Sem a extensão", withoutBody: "Abra o Back Office, procure no catálogo, encontre as quantidades, corrija o stock, guarde e volte à loja enquanto o cliente espera.", with: "Com a extensão", withBody: "Continue na mesma página que o cliente está a ver. Corrija a quantidade, reveja e guarde, sem uma segunda pesquisa.", quote: "«Já pode concluir a encomenda. Pedimos desculpa pelo incómodo.»" },
    demo: { label: "Em funcionamento", title: "Do catálogo à alteração guardada.", body: "Um fluxo real: identificar o produto, editar, utilizar a IA e confirmar o resultado.", caption: "Demonstração · 46 segundos · PrestaShop 9", fallback: "O seu navegador não permite reproduzir este vídeo." },
    trial: { label: "Comece sem risco", title: "Teste tudo. Decida depois.", body: "O teste só começa após a primeira ligação correta à sua loja PrestaShop.", cards: [["14 dias completos", "Edite, reveja, confirme, anule, dite e utilize IA com todas as funções."], ["Sem cartão", "Instale, ligue a loja e teste o fluxo real antes de comprar."], ["Modo gratuito permanente", "Depois do teste, continue a identificar produtos e a abrir a página exata do Back Office."]] },
    pricing: { label: "Licenças perpétuas", title: "Um pagamento. A sua ferramenta.", body: "Escolha pelo número de lojas e perfis do navegador. As duas licenças incluem todas as funções comerciais.", recommended: "Recomendado", multi: "Multiloja", singleAudience: "Para o proprietário ou equipa administrativa de uma loja PrestaShop.", proAudience: "Para empresas com várias lojas ou pequenas equipas multiloja.", single: ["1 loja PrestaShop", "Até 6 perfis Chrome ou Edge", "Todas as funções comerciais", "Licença perpétua, sem mensalidades"], pro: ["2 a 5 lojas PrestaShop", "Até 20 perfis Chrome ou Edge", "Todas as funções comerciais", "Licença perpétua, sem mensalidades"], choose: "Escolher", compare: "Comparar planos", note: "Impostos aplicáveis não incluídos. A compra e a entrega da licença são geridas pela Lemon Squeezy como comerciante registado." },
    benefits: { label: "O que muda", title: "Menos pesquisas. Mais catálogo resolvido.", body: "A extensão acompanha o seu trabalho sem o obrigar a abandonar o produto que está a rever.", items: [["Edite onde encontra o problema", "Abra a página pública e altere o produto sem voltar a procurá-lo."], ["Guarde através do PrestaShop", "Utilize os formulários originais e confirme o resultado."], ["Trabalhe com combinações", "Identifique a combinação selecionada e altere o stock ou a referência correta."], ["Melhore conteúdos com IA", "Trabalhe em nomes, descrições, metadados e outros campos."], ["Dite e depois decida", "Reveja a pontuação e melhore o texto antes de o inserir."], ["Mantenha o controlo", "Histórico local, preparação para anular e prompts configuráveis."]] },
    workflow: { label: "Como funciona", title: "Quatro passos. Nenhuma pesquisa duplicada.", steps: [["Ligar", "Inicie sessão no Back Office e guarde o caminho no painel lateral."], ["Navegar", "Percorra a loja como um cliente e encontre o produto a rever."], ["Editar", "Abra o controlo flutuante e altere os dados comerciais."], ["Confirmar", "Guarde através do PrestaShop e confirme automaticamente a alteração."]] },
    ai: { eyebrow: "IA dentro do Back Office", title: "Trabalhe com o campo. Não com uma caixa separada.", body: "O assistente aparece quando escreve ou seleciona conteúdo num campo nativo e prepara uma proposta antes de a inserir.", bullets: ["Melhorar, ampliar, reduzir ou corrigir.", "Otimizar para SEO e traduzir.", "Aplicar formatação quando o campo aceita HTML.", "Prompts editáveis e vários fornecedores, incluindo modelos locais."], alt: "Assistente de IA numa descrição PrestaShop", action: "Trabalhar com este campo" },
    clean: { label: "Instalação limpa", title: "A sua loja não é alterada.", items: [["Não é um módulo", "Não instala ficheiros, tabelas ou overrides no PrestaShop."], ["Utiliza a sessão real", "Trabalha com os formulários e permissões do Back Office aberto."], ["Sem resíduos", "Desinstale a extensão sem deixar código na loja."], ["Chaves sob o seu controlo", "As credenciais de IA ficam localmente no perfil do navegador."]] },
    requirements: { label: "Compatibilidade", title: "O necessário para começar.", body: "Uma configuração simples, sem acesso ao servidor nem alterações ao código.", rows: [["Navegador", "Google Chrome ou Microsoft Edge para computador"], ["PrestaShop", "Adaptadores para 1.6 · 1.7 · 8 · 9"], ["Sessão", "Back Office aberto no mesmo perfil"], ["Instalação", "Extensão do navegador, sem módulo"], ["IA", "Fornecedor HTTPS na nuvem ou modelo local compatível, opcional"], ["Interface", "Espanhol, inglês, francês, italiano, alemão e português"]] },
    trust: ["Pagamento único", "Sem subscrição", "Chrome e Edge", "PrestaShop 1.6–9", "6 idiomas", "Dados locais"],
    faq: { label: "Perguntas frequentes", title: "O essencial antes de instalar.", items: [["Quando começa o teste de 14 dias?", "Depois da primeira ligação correta ao PrestaShop, não ao instalar a extensão."], ["O que fica disponível depois do teste?", "O modo gratuito identifica o produto ou a combinação e abre a página exata do Back Office."], ["A licença é uma subscrição?", "Não. Loja e Pro são licenças perpétuas de pagamento único."], ["Instala algum módulo?", "Não. É uma extensão Chrome e Edge e não altera o código do PrestaShop."], ["Onde fica a chave de IA?", "No armazenamento local do perfil do navegador."], ["Posso editar produtos com variantes?", "Sim. A extensão deteta a combinação selecionada e utiliza os dados correspondentes."]] },
    cta: { eyebrow: "Próximo lançamento", title: "Instale, ligue e decida depois de testar.", body: "A extensão estará disponível na Chrome Web Store com teste completo de 14 dias e licenças perpétuas através da Lemon Squeezy.", button: "Comparar planos", status: "Ligação de instalação disponível após a publicação" }, legal: "Antes de instalar ou comprar, consulte em espanhol a política de privacidade e as condições de licença, suporte e devoluções.",
  },
  fr: {
    lang: "fr", title: "Frontend Product Editor + AI pour PrestaShop | Pep Logar", description: "Modifiez le produit PrestaShop affiché sans le rechercher à nouveau dans le Back-Office. Essai complet de 14 jours, mode gratuit et licences perpétuelles.", nav: ["Démo", "Essai", "Offres", "Fonctions", "Compatibilité", "Questions"],
    hero: { eyebrow: "Produit · Chrome / Edge · PrestaShop 1.6–9", promise: "Corrigez le produit que vous affichez déjà.", lede: "Modifiez prix, stock, références et contenus depuis la fiche publique, sans rechercher à nouveau le produit dans le Back-Office.", trial: "Essayer gratuitement 14 jours", guide: "Télécharger le guide visuel", demo: "Voir la démonstration", proofs: ["Aucune carte pour l'essai", "Mode gratuit permanent", "Paiement unique", "Sans module"], alt: "Modification d'un produit PrestaShop depuis sa page publique" },
    scenario: { label: "Une situation réelle", title: "« Puis-je l'acheter s'il est épuisé ? »", intro: "Un client appelle car la boutique indique une rupture. Vous savez que l'article est disponible : il faut simplement actualiser le produit.", without: "Sans l'extension", withoutBody: "Ouvrez le Back-Office, recherchez le produit, trouvez les quantités, corrigez, enregistrez et revenez à la boutique pendant que le client attend.", with: "Avec l'extension", withBody: "Restez sur la fiche que le client consulte. Corrigez la quantité, vérifiez et enregistrez, sans seconde recherche.", quote: "« Vous pouvez maintenant terminer votre commande. Toutes nos excuses. »" },
    demo: { label: "En action", title: "Du catalogue à la modification enregistrée.", body: "Un flux réel : identifier, modifier, utiliser l'IA et vérifier le résultat.", caption: "Démonstration · 46 secondes · PrestaShop 9", fallback: "Votre navigateur ne peut pas lire cette vidéo." },
    trial: { label: "Commencez sans risque", title: "Essayez tout. Décidez ensuite.", body: "L'essai commence uniquement après la première connexion réussie à votre boutique PrestaShop.", cards: [["14 jours complets", "Modifiez, vérifiez, annulez, dictez et utilisez l'IA avec toutes les fonctions."], ["Sans carte bancaire", "Installez, connectez la boutique et testez le flux réel avant d'acheter."], ["Mode gratuit permanent", "Après l'essai, identifiez toujours les produits et ouvrez leur fiche Back-Office exacte."]] },
    pricing: { label: "Licences perpétuelles", title: "Un paiement. Votre outil.", body: "Choisissez selon le nombre de boutiques et de profils. Les deux licences incluent toutes les fonctions commerciales.", recommended: "Recommandé", multi: "Multiboutique", singleAudience: "Pour le propriétaire ou l'équipe administrative d'une boutique PrestaShop.", proAudience: "Pour les entreprises qui gèrent plusieurs boutiques.", single: ["1 boutique PrestaShop", "Jusqu'à 6 profils Chrome ou Edge", "Toutes les fonctions commerciales", "Licence perpétuelle, sans mensualités"], pro: ["2 à 5 boutiques PrestaShop", "Jusqu'à 20 profils Chrome ou Edge", "Toutes les fonctions commerciales", "Licence perpétuelle, sans mensualités"], choose: "Choisir", compare: "Comparer les offres", note: "Taxes applicables en sus. L'achat et la livraison de la licence sont gérés par Lemon Squeezy en tant que commerçant officiel." },
    benefits: { label: "Ce qui change", title: "Moins de recherches. Plus de catalogue corrigé.", body: "L'extension accompagne votre travail sans vous éloigner du produit consulté.", items: [["Modifiez là où vous voyez le problème", "Ouvrez la fiche publique et modifiez le produit sans le rechercher."], ["Enregistrez via PrestaShop", "Utilisez les formulaires d'origine et vérifiez le résultat."], ["Gérez les déclinaisons", "Identifiez la déclinaison sélectionnée et modifiez le bon stock."], ["Améliorez avec l'IA", "Travaillez sur noms, descriptions, métadonnées et autres champs."], ["Dictez puis décidez", "Vérifiez la ponctuation avant d'insérer le texte."], ["Gardez le contrôle", "Historique local, préparation de l'annulation et prompts configurables."]] },
    workflow: { label: "Fonctionnement", title: "Quatre étapes. Aucune recherche en double.", steps: [["Connecter", "Connectez-vous au Back-Office et enregistrez son chemin."], ["Parcourir", "Visitez la boutique comme un client et repérez le produit."], ["Modifier", "Ouvrez le contrôle flottant et changez les données."], ["Vérifier", "Enregistrez via PrestaShop et confirmez la modification."]] },
    ai: { eyebrow: "L'IA dans le Back-Office", title: "Travaillez dans le champ. Pas dans une boîte séparée.", body: "L'assistant apparaît lorsque vous écrivez ou sélectionnez du contenu dans un champ natif et prépare une proposition avant insertion.", bullets: ["Améliorer, développer, réduire ou corriger.", "Optimiser pour le SEO et traduire.", "Appliquer une mise en forme lorsque le champ accepte le HTML.", "Prompts modifiables et plusieurs fournisseurs, y compris locaux."], alt: "Assistant IA sur une description PrestaShop", action: "Travailler avec ce champ" },
    clean: { label: "Installation propre", title: "Votre boutique n'est pas modifiée.", items: [["Ce n'est pas un module", "Aucun fichier, table ou override n'est installé."], ["Votre session réelle", "L'extension utilise les formulaires et droits du Back-Office ouvert."], ["Aucun résidu", "Désinstallez sans laisser de code dans la boutique."], ["Vos clés sous contrôle", "Les identifiants IA restent dans le profil du navigateur."]] },
    requirements: { label: "Compatibilité", title: "Ce qu'il faut pour commencer.", body: "Une mise en route simple, sans accès serveur ni modification du code.", rows: [["Navigateur", "Google Chrome ou Microsoft Edge sur ordinateur"], ["PrestaShop", "Adaptateurs 1.6 · 1.7 · 8 · 9"], ["Session", "Back-Office ouvert dans le même profil"], ["Installation", "Extension de navigateur, sans module"], ["IA", "Fournisseur HTTPS cloud ou modèle local compatible, facultatif"], ["Interface", "Espagnol, anglais, français, italien, allemand et portugais"]] },
    trust: ["Paiement unique", "Sans abonnement", "Chrome et Edge", "PrestaShop 1.6–9", "6 langues", "Données locales"],
    faq: { label: "Questions fréquentes", title: "L'essentiel avant l'installation.", items: [["Quand commence l'essai de 14 jours ?", "Après la première connexion réussie à PrestaShop, et non à l'installation."], ["Que reste-t-il après l'essai ?", "Le mode gratuit identifie le produit ou la déclinaison et ouvre sa fiche Back-Office exacte."], ["La licence est-elle un abonnement ?", "Non. Boutique et Pro sont des licences perpétuelles à paiement unique."], ["Un module est-il installé ?", "Non. Il s'agit d'une extension Chrome et Edge qui ne modifie pas PrestaShop."], ["Où la clé IA est-elle conservée ?", "Dans le stockage local du profil du navigateur."], ["Puis-je modifier les produits avec variantes ?", "Oui. L'extension détecte la déclinaison sélectionnée."]] },
    cta: { eyebrow: "Prochain lancement", title: "Installez, connectez et décidez après l'essai.", body: "L'extension sera disponible sur le Chrome Web Store avec 14 jours d'essai complet et des licences perpétuelles via Lemon Squeezy.", button: "Comparer les offres", status: "Lien d'installation disponible après publication" }, legal: "Avant l'installation ou l'achat, consultez en espagnol la politique de confidentialité et les conditions de licence, d'assistance et de remboursement.",
  },
  it: {
    lang: "it", title: "Frontend Product Editor + AI per PrestaShop | Pep Logar", description: "Modifica il prodotto PrestaShop che stai già guardando senza cercarlo di nuovo nel Back Office. Prova completa di 14 giorni, modalità gratuita e licenze perpetue.", nav: ["Demo", "Prova", "Piani", "Funzioni", "Compatibilità", "Domande"],
    hero: { eyebrow: "Prodotto · Chrome / Edge · PrestaShop 1.6–9", promise: "Correggi il prodotto che stai già guardando.", lede: "Modifica prezzi, stock, riferimenti e contenuti dalla pagina pubblica del prodotto, senza cercarlo di nuovo nel Back Office.", trial: "Prova gratis per 14 giorni", guide: "Scarica la guida visiva", demo: "Guarda la demo", proofs: ["Nessuna carta per la prova", "Modalità gratuita permanente", "Pagamento unico", "Nessun modulo"], alt: "Modifica di un prodotto PrestaShop dalla pagina pubblica" },
    scenario: { label: "Una situazione reale", title: "«Posso acquistarlo se non è disponibile?»", intro: "Un cliente chiama perché il negozio indica stock esaurito. Sai che l'articolo c'è: bisogna solo aggiornare il prodotto.", without: "Senza l'estensione", withoutBody: "Apri il Back Office, cerca il prodotto, trova le quantità, correggi, salva e torna al negozio mentre il cliente aspetta.", with: "Con l'estensione", withBody: "Rimani sulla pagina che vede il cliente. Correggi la quantità, controlla e salva senza una seconda ricerca.", quote: "«Ora può completare l'ordine. Ci scusiamo per l'inconveniente.»" },
    demo: { label: "In funzione", title: "Dal catalogo alla modifica salvata.", body: "Un flusso reale: identifica il prodotto, modifica, usa l'IA e verifica il risultato.", caption: "Dimostrazione · 46 secondi · PrestaShop 9", fallback: "Il browser non può riprodurre questo video." },
    trial: { label: "Inizia senza rischi", title: "Prova tutto. Decidi dopo.", body: "La prova inizia solo dopo la prima connessione riuscita al tuo negozio PrestaShop.", cards: [["14 giorni completi", "Modifica, controlla, annulla, detta e usa l'IA con tutte le funzioni."], ["Senza carta", "Installa, collega il negozio e prova il flusso reale prima di acquistare."], ["Modalità gratuita permanente", "Dopo la prova, continua a identificare i prodotti e ad aprire la pagina Back Office esatta."]] },
    pricing: { label: "Licenze perpetue", title: "Un pagamento. Il tuo strumento.", body: "Scegli in base al numero di negozi e profili. Entrambe le licenze includono tutte le funzioni commerciali.", recommended: "Consigliato", multi: "Multinegozio", singleAudience: "Per il proprietario o il team amministrativo di un negozio PrestaShop.", proAudience: "Per attività che gestiscono più negozi.", single: ["1 negozio PrestaShop", "Fino a 6 profili Chrome o Edge", "Tutte le funzioni commerciali", "Licenza perpetua, nessun canone mensile"], pro: ["Da 2 a 5 negozi PrestaShop", "Fino a 20 profili Chrome o Edge", "Tutte le funzioni commerciali", "Licenza perpetua, nessun canone mensile"], choose: "Scegli", compare: "Confronta i piani", note: "Imposte applicabili escluse. Acquisto e consegna della licenza sono gestiti da Lemon Squeezy come merchant of record." },
    benefits: { label: "Cosa cambia", title: "Meno ricerche. Più catalogo risolto.", body: "L'estensione segue il tuo flusso senza costringerti a lasciare il prodotto che stai controllando.", items: [["Modifica dove trovi il problema", "Apri la pagina pubblica e cambia il prodotto senza cercarlo di nuovo."], ["Salva tramite PrestaShop", "Usa i moduli originali e verifica il risultato."], ["Gestisci le combinazioni", "Riconosci la combinazione selezionata e modifica lo stock corretto."], ["Migliora con l'IA", "Lavora su nomi, descrizioni, metadati e altri campi."], ["Detta, poi decidi", "Controlla la punteggiatura prima di inserire il testo."], ["Mantieni il controllo", "Cronologia locale, preparazione annullamento e prompt configurabili."]] },
    workflow: { label: "Come funziona", title: "Quattro passaggi. Nessuna ricerca doppia.", steps: [["Collega", "Accedi al Back Office e salva il percorso nel pannello laterale."], ["Naviga", "Visita il negozio come un cliente e individua il prodotto."], ["Modifica", "Apri il controllo mobile e cambia i dati commerciali."], ["Verifica", "Salva tramite PrestaShop e conferma automaticamente la modifica."]] },
    ai: { eyebrow: "IA dentro il Back Office", title: "Lavora nel campo. Non in una casella separata.", body: "L'assistente appare quando scrivi o selezioni contenuto in un campo nativo e prepara una proposta prima dell'inserimento.", bullets: ["Migliora, amplia, riduci o correggi.", "Ottimizza per SEO e traduci.", "Applica la formattazione quando il campo supporta HTML.", "Prompt modificabili e diversi provider, anche locali."], alt: "Assistente IA su una descrizione PrestaShop", action: "Lavora con questo campo" },
    clean: { label: "Installazione pulita", title: "Il tuo negozio non viene modificato.", items: [["Non è un modulo", "Non installa file, tabelle o override in PrestaShop."], ["Usa la sessione reale", "Lavora con moduli e autorizzazioni del Back Office aperto."], ["Nessun residuo", "Disinstalla senza lasciare codice nel negozio."], ["Chiavi sotto controllo", "Le credenziali IA restano nel profilo del browser."]] },
    requirements: { label: "Compatibilità", title: "Cosa serve per iniziare.", body: "Configurazione semplice, senza accesso al server né modifiche al codice.", rows: [["Browser", "Google Chrome o Microsoft Edge desktop"], ["PrestaShop", "Adattatori 1.6 · 1.7 · 8 · 9"], ["Sessione", "Back Office aperto nello stesso profilo"], ["Installazione", "Estensione browser, nessun modulo"], ["IA", "Provider HTTPS cloud o modello locale compatibile, opzionale"], ["Interfaccia", "Spagnolo, inglese, francese, italiano, tedesco e portoghese"]] },
    trust: ["Pagamento unico", "Nessun abbonamento", "Chrome ed Edge", "PrestaShop 1.6–9", "6 lingue", "Dati locali"],
    faq: { label: "Domande frequenti", title: "L'essenziale prima dell'installazione.", items: [["Quando inizia la prova di 14 giorni?", "Dopo la prima connessione riuscita a PrestaShop, non all'installazione."], ["Cosa rimane dopo la prova?", "La modalità gratuita identifica il prodotto o la combinazione e apre la pagina Back Office esatta."], ["La licenza è un abbonamento?", "No. Negozio e Pro sono licenze perpetue con pagamento unico."], ["Installa un modulo?", "No. È un'estensione Chrome ed Edge e non modifica PrestaShop."], ["Dove viene salvata la chiave IA?", "Nella memoria locale del profilo del browser."], ["Posso modificare prodotti con varianti?", "Sì. L'estensione rileva la combinazione selezionata."]] },
    cta: { eyebrow: "Prossimo lancio", title: "Installa, collega e decidi dopo la prova.", body: "L'estensione sarà disponibile nel Chrome Web Store con prova completa di 14 giorni e licenze perpetue tramite Lemon Squeezy.", button: "Confronta i piani", status: "Link di installazione disponibile dopo la pubblicazione" }, legal: "Prima di installare o acquistare, consulta in spagnolo l'informativa sulla privacy e le condizioni di licenza, assistenza e rimborso.",
  },
  de: {
    lang: "de", title: "Frontend Product Editor + AI für PrestaShop | Pep Logar", description: "Bearbeiten Sie das PrestaShop-Produkt, das Sie gerade sehen, ohne es im Backoffice erneut zu suchen. 14 Tage Volltest, kostenloser Modus und Dauerlizenzen.", nav: ["Demo", "Test", "Pakete", "Funktionen", "Kompatibilität", "Fragen"],
    hero: { eyebrow: "Produkt · Chrome / Edge · PrestaShop 1.6–9", promise: "Korrigieren Sie das Produkt, das Sie bereits sehen.", lede: "Bearbeiten Sie Preise, Bestand, Referenzen und Inhalte direkt auf der öffentlichen Produktseite, ohne das Produkt erneut im Backoffice zu suchen.", trial: "14 Tage kostenlos testen", guide: "Visuellen Leitfaden laden", demo: "Demo ansehen", proofs: ["Keine Karte für den Test", "Dauerhaft kostenloser Modus", "Einmalzahlung", "Keine Module"], alt: "Bearbeitung eines PrestaShop-Produkts auf seiner öffentlichen Seite" },
    scenario: { label: "Eine echte Situation", title: "„Kann ich es kaufen, obwohl kein Bestand angezeigt wird?“", intro: "Ein Kunde ruft an, weil der Shop keinen Bestand zeigt. Sie wissen, dass der Artikel verfügbar ist – das Produkt muss nur aktualisiert werden.", without: "Ohne Erweiterung", withoutBody: "Backoffice öffnen, Produkt suchen, Mengen finden, Bestand korrigieren, speichern und zum Shop zurückkehren, während der Kunde wartet.", with: "Mit Erweiterung", withBody: "Bleiben Sie auf derselben Seite wie der Kunde. Menge ändern, prüfen und speichern – ohne zweite Suche.", quote: "„Sie können die Bestellung jetzt abschließen. Entschuldigen Sie bitte die Umstände.“" },
    demo: { label: "Im Einsatz", title: "Vom Katalog zur gespeicherten Änderung.", body: "Ein echter Ablauf: Produkt erkennen, bearbeiten, KI nutzen und Ergebnis prüfen.", caption: "Demo · 46 Sekunden · PrestaShop 9", fallback: "Ihr Browser kann dieses Video nicht abspielen." },
    trial: { label: "Ohne Risiko starten", title: "Alles testen. Danach entscheiden.", body: "Der Test beginnt erst nach der ersten erfolgreichen Verbindung mit Ihrem PrestaShop-Shop.", cards: [["14 volle Tage", "Bearbeiten, prüfen, rückgängig machen, diktieren und KI mit allen Funktionen nutzen."], ["Keine Karte erforderlich", "Installieren, Shop verbinden und den echten Ablauf vor dem Kauf testen."], ["Dauerhaft kostenlos", "Nach dem Test Produkte weiterhin erkennen und die exakte Backoffice-Seite öffnen."]] },
    pricing: { label: "Dauerlizenzen", title: "Eine Zahlung. Ihr Werkzeug.", body: "Wählen Sie nach Anzahl der Shops und Browserprofile. Beide Lizenzen enthalten alle kommerziellen Funktionen.", recommended: "Empfohlen", multi: "Mehrere Shops", singleAudience: "Für Eigentümer oder Verwaltungsteam eines PrestaShop-Shops.", proAudience: "Für Unternehmen mit mehreren Shops oder kleine Multi-Shop-Teams.", single: ["1 PrestaShop-Shop", "Bis zu 6 Chrome- oder Edge-Profile", "Alle kommerziellen Funktionen", "Dauerlizenz ohne Monatsgebühr"], pro: ["2 bis 5 PrestaShop-Shops", "Bis zu 20 Chrome- oder Edge-Profile", "Alle kommerziellen Funktionen", "Dauerlizenz ohne Monatsgebühr"], choose: "Wählen", compare: "Pakete vergleichen", note: "Zuzüglich anwendbarer Steuern. Kauf und Lizenzbereitstellung erfolgen durch Lemon Squeezy als Merchant of Record." },
    benefits: { label: "Was sich ändert", title: "Weniger suchen. Mehr Katalog erledigen.", body: "Die Erweiterung folgt Ihrem Arbeitsablauf, ohne Sie vom gerade geprüften Produkt wegzuführen.", items: [["Dort bearbeiten, wo das Problem auffällt", "Öffentliche Seite öffnen und Produkt ohne erneute Suche ändern."], ["Über PrestaShop speichern", "Originalformulare verwenden und Ergebnis prüfen."], ["Kombinationen verwalten", "Gewählte Kombination erkennen und richtigen Bestand bearbeiten."], ["Inhalte mit KI verbessern", "Namen, Beschreibungen, Metadaten und weitere Felder bearbeiten."], ["Diktieren, dann entscheiden", "Zeichensetzung prüfen und Text vor dem Einfügen verbessern."], ["Kontrolle behalten", "Lokaler Verlauf, Rückgängig-Vorbereitung und konfigurierbare Prompts."]] },
    workflow: { label: "So funktioniert es", title: "Vier Schritte. Keine doppelte Suche.", steps: [["Verbinden", "Im Backoffice anmelden und den Pfad im Seitenpanel speichern."], ["Navigieren", "Shop wie ein Kunde besuchen und das Produkt erkennen."], ["Bearbeiten", "Schwebendes Steuerelement öffnen und Daten ändern."], ["Prüfen", "Über PrestaShop speichern und die Änderung automatisch bestätigen."]] },
    ai: { eyebrow: "KI im Backoffice", title: "Im Feld arbeiten. Nicht in einem separaten Fenster.", body: "Der Assistent erscheint beim Schreiben oder Markieren in einem Originalfeld und erstellt vor dem Einfügen einen Vorschlag.", bullets: ["Verbessern, erweitern, kürzen oder korrigieren.", "Für SEO optimieren und übersetzen.", "Formatierung anwenden, wenn HTML unterstützt wird.", "Bearbeitbare Prompts und mehrere Anbieter, auch lokal."], alt: "KI-Assistent in einer PrestaShop-Beschreibung", action: "Mit diesem Feld arbeiten" },
    clean: { label: "Saubere Installation", title: "Ihr Shop wird nicht verändert.", items: [["Kein Modul", "Keine Dateien, Tabellen oder Overrides in PrestaShop."], ["Nutzt Ihre echte Sitzung", "Arbeitet mit Formularen und Rechten des geöffneten Backoffice."], ["Keine Rückstände", "Deinstallieren, ohne Code im Shop zu hinterlassen."], ["Schlüssel unter Ihrer Kontrolle", "KI-Zugangsdaten bleiben im Browserprofil."]] },
    requirements: { label: "Kompatibilität", title: "Das benötigen Sie zum Start.", body: "Einfache Einrichtung ohne Serverzugriff und ohne Änderung des Shopcodes.", rows: [["Browser", "Google Chrome oder Microsoft Edge für Desktop"], ["PrestaShop", "Adapter für 1.6 · 1.7 · 8 · 9"], ["Sitzung", "Backoffice im selben Browserprofil geöffnet"], ["Installation", "Browsererweiterung, kein PrestaShop-Modul"], ["KI", "Optionaler HTTPS-Cloudanbieter oder kompatibles lokales Modell"], ["Oberfläche", "Spanisch, Englisch, Französisch, Italienisch, Deutsch und Portugiesisch"]] },
    trust: ["Einmalzahlung", "Kein Abo", "Chrome und Edge", "PrestaShop 1.6–9", "6 Sprachen", "Lokale Daten"],
    faq: { label: "Häufige Fragen", title: "Das Wichtigste vor der Installation.", items: [["Wann beginnt der 14-Tage-Test?", "Nach der ersten erfolgreichen PrestaShop-Verbindung, nicht bei der Installation."], ["Was bleibt nach dem Test?", "Der kostenlose Modus erkennt Produkt oder Kombination und öffnet die exakte Backoffice-Seite."], ["Ist die Lizenz ein Abonnement?", "Nein. Shop und Pro sind Dauerlizenzen mit Einmalzahlung."], ["Wird ein Modul installiert?", "Nein. Es ist eine Chrome- und Edge-Erweiterung und verändert PrestaShop nicht."], ["Wo wird der KI-Schlüssel gespeichert?", "Im lokalen Speicher des Browserprofils."], ["Kann ich Varianten bearbeiten?", "Ja. Die Erweiterung erkennt die ausgewählte Kombination."]] },
    cta: { eyebrow: "Demnächst", title: "Installieren, verbinden und nach dem Test entscheiden.", body: "Die Erweiterung erscheint im Chrome Web Store mit 14 Tagen Volltest und Dauerlizenzen über Lemon Squeezy.", button: "Pakete vergleichen", status: "Installationslink nach Veröffentlichung verfügbar" }, legal: "Lesen Sie vor Installation oder Kauf die spanische Datenschutzerklärung sowie die Lizenz-, Support- und Erstattungsbedingungen.",
  },
};

export function localizedMetadata(locale: Exclude<ProductLocale, "es">): Metadata {
  const value = copy[locale];
  const languages = Object.fromEntries(Object.entries(productLocalePaths).map(([key, path]) => [key === "pt" ? "pt-PT" : key, path]));
  return {
    title: value.title,
    description: value.description,
    alternates: { canonical: productLocalePaths[locale], languages },
    openGraph: { title: "Pep Logar Frontend Product Editor + AI", description: value.description, type: "website", locale: value.lang.replace("-", "_"), images: [{ url: "/productos/fpe-ai/og-product.png", width: 1732, height: 908, alt: "Pep Logar Frontend Product Editor + AI" }] },
    twitter: { card: "summary_large_image", title: "Pep Logar Frontend Product Editor + AI", description: value.description, images: ["/productos/fpe-ai/og-product.png"] },
    other: { "content-language": value.lang },
  };
}

export function LocalizedProductPage({ locale }: { locale: Exclude<ProductLocale, "es"> }) {
  const c = copy[locale];
  const video = `/productos/fpe-ai/demo-${locale}.mp4`;
  const ids = ["demonstration", "trial", "plans", "features", "compatibility", "questions"];
  const structuredData = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Pep Logar Frontend Product Editor + AI for PrestaShop", applicationCategory: "BusinessApplication", operatingSystem: "Google Chrome, Microsoft Edge", description: c.description, url: `https://aisolutions.peplogar.com${productLocalePaths[locale]}`, image: "https://aisolutions.peplogar.com/productos/fpe-ai/og-product.png", softwareVersion: "1.27.0", inLanguage: c.lang, offers: { "@type": "AggregateOffer", priceCurrency: "EUR", lowPrice: "89", highPrice: "179", offerCount: "2" }, publisher: { "@type": "Organization", name: "Pep Logar AI Solutions", url: "https://aisolutions.peplogar.com/" } };

  return (
    <main className="product-page" lang={c.lang}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
      <SiteHeader current="products" locale={locale} />
      <section className="product-hero shell">
        <div className="product-hero-copy">
          <ProductLanguageSwitcher current={locale} />
          <p className="eyebrow"><span /> {c.hero.eyebrow}</p>
          <h1><span className="product-brand">Pep Logar</span>Frontend Product<br /><em>Editor + AI</em></h1>
          <p className="product-hero-promise">{c.hero.promise}</p><p className="product-hero-lede">{c.hero.lede}</p>
          <div className="hero-actions"><a className="button button-dark" href="#trial">{c.hero.trial} <span>↓</span></a><a className="text-link" href="/productos/fpe-ai/Pep-Logar-FPE-AI-Guia-visual.pdf" download>{c.hero.guide} <span>↓</span></a><a className="text-link" href="#demonstration">{c.hero.demo} <span>↓</span></a></div>
          <div className="product-proof">{c.hero.proofs.map(item => <span key={item}>{item}</span>)}</div>
        </div>
        <div className="product-hero-visual"><img src="/productos/fpe-ai/frontoffice-editor.png" alt={c.hero.alt} /><div className="product-floating-pill">✎ Frontend Product Editor <b>#1</b></div><div className="product-version-card"><small>PRESTASHOP</small><strong>1.6 · 1.7 · 8 · 9</strong></div></div>
      </section>
      <nav className="product-section-nav" aria-label="Product sections"><div className="shell">{c.nav.map((label, index) => <a key={label} href={`#${ids[index]}`}>{label}</a>)}</div></nav>

      <section className="product-use-case"><div className="shell product-use-case-grid"><div className="product-use-case-lead"><p className="section-label">{c.scenario.label}</p><span className="use-case-icon" aria-hidden="true">☎</span><h2>{c.scenario.title}</h2><p>{c.scenario.intro}</p></div><div className="product-use-case-story"><article><span>{c.scenario.without}</span><p>{c.scenario.withoutBody}</p></article><article className="product-use-case-fast"><span>{c.scenario.with}</span><p>{c.scenario.withBody}</p></article><strong>{c.scenario.quote}</strong></div></div></section>

      <section className="product-demo" id="demonstration"><div className="shell"><div className="product-section-heading"><p className="section-label">{c.demo.label}</p><div><h2>{c.demo.title}</h2><p>{c.demo.body}</p></div></div><div className="video-frame"><video controls preload="metadata" poster="/productos/fpe-ai/frontoffice-pill.png"><source src={video} type="video/mp4" /><track default kind="captions" src={`/productos/fpe-ai/demo-${locale}.vtt`} srcLang={c.lang} label={locale.toUpperCase()} />{c.demo.fallback}</video><span className="video-caption">{c.demo.caption}</span></div></div></section>

      <section className="product-trial shell" id="trial"><div className="product-section-heading"><p className="section-label">{c.trial.label}</p><div><h2>{c.trial.title}</h2><p>{c.trial.body}</p></div></div><div className="trial-grid">{c.trial.cards.map(([title, body], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><strong>{title}</strong><p>{body}</p></article>)}</div></section>

      <section className="product-pricing" id="plans"><div className="shell"><div className="product-section-heading light-heading"><p className="section-label">{c.pricing.label}</p><div><h2>{c.pricing.title}</h2><p>{c.pricing.body}</p></div></div><div className="pricing-grid"><article className="pricing-card pricing-card-featured"><div className="pricing-card-heading"><div><span className="pricing-badge">{c.pricing.recommended}</span><h3>Shop</h3></div><p><strong>89 €</strong><small>one-time</small></p></div><p className="pricing-audience">{c.pricing.singleAudience}</p><ul>{c.pricing.single.map(item => <li key={item}>{item}</li>)}</ul><a className="button button-light" href={fpeCheckoutLinks.store} target="_blank" rel="noopener noreferrer">{c.pricing.choose} Shop <span>↗</span></a></article><article className="pricing-card"><div className="pricing-card-heading"><div><span className="pricing-badge pricing-badge-secondary">{c.pricing.multi}</span><h3>Pro</h3></div><p><strong>179 €</strong><small>one-time</small></p></div><p className="pricing-audience">{c.pricing.proAudience}</p><ul>{c.pricing.pro.map(item => <li key={item}>{item}</li>)}</ul><a className="button button-outline-light" href={fpeCheckoutLinks.pro} target="_blank" rel="noopener noreferrer">{c.pricing.choose} Pro <span>↗</span></a></article></div><p className="commercial-proof">{c.pricing.note}</p></div></section>

      <section className="product-benefits shell" id="features"><div className="product-section-heading"><p className="section-label">{c.benefits.label}</p><div><h2>{c.benefits.title}</h2><p>{c.benefits.body}</p></div></div><div className="benefit-grid">{c.benefits.items.map(([title, body], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>

      <section className="product-workflow"><div className="shell"><div className="product-section-heading light-heading"><p className="section-label">{c.workflow.label}</p><div><h2>{c.workflow.title}</h2></div></div><ol className="product-steps">{c.workflow.steps.map(([title, body], index) => <li key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></div></section>

      <section className="product-ai shell"><div className="product-ai-copy"><p className="eyebrow"><span /> {c.ai.eyebrow}</p><h2>{c.ai.title}</h2><p>{c.ai.body}</p><ul>{c.ai.bullets.map(item => <li key={item}>{item}</li>)}</ul></div><div className="product-ai-visual"><img src="/productos/fpe-ai/ai-description.png" alt={c.ai.alt} /><span>✦ {c.ai.action}</span></div></section>

      <section className="product-clean"><div className="shell product-clean-grid"><div><p className="section-label">{c.clean.label}</p><h2>{c.clean.title}</h2></div><div className="clean-points">{c.clean.items.map(([title, body], index) => <article key={title}><strong>{String(index + 1).padStart(2, "0")}</strong><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></div></section>

      <section className="product-requirements shell" id="compatibility"><div className="requirements-copy"><p className="section-label">{c.requirements.label}</p><h2>{c.requirements.title}</h2><p>{c.requirements.body}</p></div><dl>{c.requirements.rows.map(([term, detail]) => <div key={term}><dt>{term}</dt><dd>{detail}</dd></div>)}</dl></section>
      <section className="product-trust shell">{c.trust.map(item => <span key={item}>{item}</span>)}</section>

      <section className="product-faq shell" id="questions"><div className="product-section-heading"><p className="section-label">{c.faq.label}</p><div><h2>{c.faq.title}</h2></div></div><div className="faq-list">{c.faq.items.map(([question, answer], index) => <details key={question}><summary><span>{String(index + 1).padStart(2, "0")}</span>{question}</summary><p>{answer}</p></details>)}</div></section>

      <section className="product-cta shell" id="availability"><div><p className="eyebrow light"><span /> {c.cta.eyebrow}</p><h2>{c.cta.title}</h2><p>{c.cta.body}</p></div><div className="product-cta-actions"><a className="button button-light" href="#plans">{c.cta.button} <span>↑</span></a><span className="availability-status">{c.cta.status}</span></div></section>
      <p className="product-privacy-link shell">{c.legal} <a href="/privacidad/frontend-product-editor-ai/">Privacy</a> · <a href="/condiciones/frontend-product-editor-ai/">Terms</a></p>
      <SiteFooter locale={locale} />
    </main>
  );
}
